---
drivers:
  daemon:
    features:
      operator:
        - name: "driver:podman"
    driver:
      podman:
        name: podman
        type: builtin
        handlerData:
          shortName: hd-driver-podman

systems:
  podman:
    functions:
      start_pod:
        driver: podman
        rawAction: start_pod
        parameters:
          pod_spec: $?ctx.podman_pod_spec
          containers: $?ctx.podman_containers
          uri: $?sysData.uri
          identity: $?sysData.identity
          with_work_volume: $?ctx.podman_with_work_volume
          use_work_volume: $?ctx.podman_use_work_volume
          work_volume_mount_point: $?ctx.podman_work_volume_mount_point
        export:
          podman_pod_id: $data.pod_id
      wait_pod:
        driver: podman
        rawAction: wait_pod
        parameters:
          pod_id: $ctx.podman_pod_id
          uri: $?sysData.uri
          identity: $?sysData.identity
        export:
          podman_pod_status: $labels.status
      get_pod_log:
        driver: podman
        rawAction: get_pod_log
        parameters:
          pod_id: $ctx.podman_pod_id
          uri: $?sysData.uri
          identity: $?sysData.identity
          delete_on_success: '{{ empty .ctx.podman_delete_on_success | not | return }}'
        export:
          podman_pod_log: $data.all
      create_volume:
        driver: podman
        rawAction: create_volume
        parameters:
          name: $?ctx.podman_volume_name
          volume_spec: $?ctx.podman_volume_spec
          uri: $?sysData.uri
          identity: $?sysData.identity
        export:
          podman_volume_name: $data.volume_name
      delete_volume:
        driver: podman
        rawAction: delete_volume
        parameters:
          volume_name: $ctx.podman_volume_name
          force: $?ctx.podman_volume_force
          uri: $?sysData.uri
          identity: $?sysData.identity

workflows:
  run_podman:
    with:
      podman_system-: podman
    steps:
    - call_function: '{{ .ctx.podman_system}}.start_pod'
    - call_workflow: $?ctx.podman_on_start
    - call_function: '{{ .ctx.podman_system}}.wait_pod'
    - call_function: '{{ .ctx.podman_system}}.get_pod_log'

  check_slack_interact:
    call_workflow: slack_ask
    with:
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: "Let's test the slack interact!"

